
services:
  - type: web
    name: news-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port 8000"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: your-database
          property: connectionString
      - key: OPENAI_API_KEY
        sync: false
