services:
  - type: web
    name: news-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn backend.main:app --host 0.0.0.0 --port 8000"
    envVars:
      - key: OPENAI_API_KEY
        value: YOUR_OPENAI_API_KEY
      - key: DATABASE_URL
        value: YOUR_NEON_DATABASE_URL
      - key: GOOGLE_TRANSLATE_API_KEY
        value: OPTIONAL_IF_NEEDED

  - type: worker
    name: telegram-news-bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python telegram_bot/bot.py"
    envVars:
      - key: BOT_TOKEN
        value: YOUR_TELEGRAM_BOT_TOKEN
      - key: DATABASE_URL
        value: YOUR_NEON_DATABASE_URL

  - type: static
    name: news-frontend
    buildCommand: "npm install && npm run build"
    staticPublishPath: frontend/dist